apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: {{ .Values.global.env }}-adminer
  name: {{ .Values.global.env }}-adminer
spec:
  ports:
    - name: "9030"
      port: 9030
      targetPort: 8080
  selector:
    io.kompose.service: {{ .Values.global.env }}-adminer
status:
  loadBalancer: {}
