apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.global.env }}-adminer
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: {{ .Values.global.env }}-adminer
  strategy: {}
  template:
    metadata:
      labels:
        io.kompose.service: {{ .Values.global.env }}-adminer
    spec:
      containers:
        - image: adminer
          name: {{ .Values.global.env }}-adminer
          ports:
            - containerPort: 8080
          resources: {}
      restartPolicy: Always
status: {}
