apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: {{ .Values.global.env }}-db
  name: {{ .Values.global.env }}-db
spec:
  ports:
    - name: "3306"
      port: 3306
      targetPort: 3306
  selector:
    io.kompose.service: {{ .Values.global.env }}-db
status:
  loadBalancer: {}
