apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: {{ .Values.global.env }}-localstack
  name: {{ .Values.global.env }}-localstack
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: {{ .Values.global.env }}-localstack
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: {{ .Values.global.env }}-localstack
    spec:
      containers:
        - env:
            - name: AWS_DEFAULT_REGION
              value: us-east-1
            - name: EDGE_PORT
              value: "4566"
            - name: SERVICES
              value: s3
          image: localstack/localstack:latest
          name: {{ .Values.global.env }}-localstack
          resources:
            requests:
              cpu: "500m"
              memory: "500Mi"
            limits:
              cpu: "1000m"
              memory: "600Mi"
          ports:
            - containerPort: 4566
            - containerPort: 4567
            - containerPort: 4568
            - containerPort: 4569
            - containerPort: 4570
            - containerPort: 4571
            - containerPort: 4572
            - containerPort: 4573
            - containerPort: 4574
            - containerPort: 4575
            - containerPort: 4576
            - containerPort: 4577
            - containerPort: 4578
            - containerPort: 4579
            - containerPort: 4580
            - containerPort: 4581
            - containerPort: 4582
            - containerPort: 4583
          resources: {}
          volumeMounts:
            - mountPath: /tmp/localstack
              name: {{ .Values.global.env }}-localstack
            - mountPath: /var/run/docker.sock
              name: {{ .Values.global.env }}-localstack-claim1
      restartPolicy: Always
      volumes:
        - name: {{ .Values.global.env }}-localstack
          persistentVolumeClaim:
            claimName: {{ .Values.global.env }}-localstack
        - name: {{ .Values.global.env }}-localstack-claim1
          persistentVolumeClaim:
            claimName: {{ .Values.global.env }}-localstack-claim1
status: {}
