apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: {{ .Values.global.env }}-spring
  name: {{ .Values.global.env }}-spring
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
  selector:
    io.kompose.service: {{ .Values.global.env }}-spring
status:
  loadBalancer: {}
