apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.global.env }}-adminer
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: adminer
  strategy: {}
  template:
    metadata:
      labels:
        io.kompose.service: {{ .Values.global.env }}-adminer
    spec:
      containers:
        - image: adminer
          name: {{ .Values.global.env }}-adminer
          ports:
            - containerPort: 8080
          resources: {}
      restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.global.env }}-adminer
spec:
  ports:
    - name: "9030"
      port: 9030
      targetPort: 8080
  selector:
    io.kompose.service: {{ .Values.global.env }}-adminer
status:
  loadBalancer: {}
