name: Workflow Test Build Push

on:
  push:
  pull_request:
    types: [opened, synchronize, reopened, closed]
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      file: docker-compose.build-test.yml
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Test with Maven
        run: mvn test -Dspring.profiles.active=test
  build-and-deploy:
    #if: github.event.pull_request.merged == true
    name: Building and deploying on Docker Hub
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 
      - name: Login to Dockerhub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and Push db
        run: |
          docker build -f Dockerfiles/Dockerfile-mysql -t mbza/dyno-nuggets-db .
          docker push mbza/dyno-nuggets-db:latest
      - name: Build and Push spring
        run: |
          docker build -f Dockerfiles/Dockerfile-spring -t mbza/dyno-nuggets-app .
          docker push mbza/dyno-nuggets-app:latest